"""Type stubs for the thegent_shm Rust extension module."""

from typing import Any

def py_init_shm(path: str) -> None: ...
def update_provider(provider: str, request_count: int, success_count: int, latency_ms: int) -> None: ...
def get_provider_metrics(provider: str) -> dict[str, Any] | None: ...
def record_resource_usage(pid: int, cpu_percent: float, memory_kb: int) -> None: ...
def award_xp(amount: int) -> None: ...
def get_xp_state() -> dict[str, Any] | None: ...
def record_failure(target: str, category: int) -> None: ...
def set_health_score(score: float) -> None: ...
def get_health_score() -> float: ...
def update_router_metrics(lifecycle_inc: int, thegent_inc: int, changes_inc: int, hysteresis_inc: int) -> None: ...
def get_router_metrics() -> dict[str, Any] | None: ...
