def ratio(s1: str, s2: str, *, processor: object = ..., score_cutoff: float = ...) -> float: ...
def partial_ratio(s1: str, s2: str, *, processor: object = ..., score_cutoff: float = ...) -> float: ...
def token_sort_ratio(s1: str, s2: str, *, processor: object = ..., score_cutoff: float = ...) -> float: ...
def token_set_ratio(s1: str, s2: str, *, processor: object = ..., score_cutoff: float = ...) -> float: ...
def WRatio(s1: str, s2: str, *, processor: object = ..., score_cutoff: float = ...) -> float: ...
